on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: Env name
        type: string
        default: "prod"
      cloudfront_invalidation:
        required: false
        description: "Path or pattern within your web artifact for which to create a Cloudfront invalidation"
        type: string
        default: "/*"
    secrets:
      AWS_S3_BUCKET_NAME:
        required: true
        description: Name of the S3 bucket to upload static web build artifacts to
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS IAM Access Key ID for accessing resources
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS IAM Secret Access Key for accessing resources
      AWS_CLOUDFRONT_DISTRIBUTION_ID:
        required: true
        description: ID of the Cloudfront Distribution used by this artifact
      AWS_REGION:
        required: true
        description: AWS deployment region
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'prod' }}
    steps:
      - name: Download artifact from last successful CI run
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{inputs.environment}}-${{ github.run_number }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete

      - name: Invalidate CloudFront Distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "${{ inputs.cloudfront_invalidation }}"